version: "2"
services:
  kong-database:
    image: postgres
    container_name: kong-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
  kong:
    image: kong:0.9.9
    container_name: kong-core
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    restart: always
    ports:
      - "20801:8000"
      - "20802:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    links:
      - kong-database
  kong-ui:
    image: pgbi/kong-dashboard
    container_name: kong-ui
    restart: always
    links:
      - kong-core
    ports:
      - "8080:8080"
