services:
  kongdatabase:
    image: cassandra:3
    container_name: kong-database
    restart: always
    ports:
      - "9042:9042"
  kongui:
    image: pgbi/kong-dashboard:latest
    container_name: kong-ui
    restart: always
    links: 
      - kong
    ports:
      - "8002:8080"
  kong:
    image: kong:latest
    container_name: kong
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PG_HOST=kong-database
    restart: always
    ports:
      - "8001:8001"
      - "8000:8000"
      - "8443:8443"
      - "7946:7946"
      - "7946:7946/udp"
    links:
      - kong-database
